local broadcast = require "main.broadcast"

function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("left_button") then
		broadcast[hash("group_A")]:send("force", {force = vmath.vector3(0, 500, 0)})
	elseif action_id == hash("right_button") then
		broadcast[hash("group_B")]:send("force", {force = vmath.vector3(0, 500, 0)})
	end
end